/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.12
 * Generated at: 2019-12-10 10:08:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Date;

public final class Issue_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write('	');

		String user=(String)session.getAttribute("user");
	if(request.getParameterValues("bookid") != null)
	{			
		
		
		String str[] = request.getParameterValues("bookid");
		
		Class.forName("com.mysql.jdbc.Driver");
		Connection con=DriverManager.getConnection(
			"jdbc:mysql://localhost:3307/library",
							"root","root");

			for(String s : str)
			{
			String sql = "SELECT Username FROM TranBook WHERE BookId = ? ";
			PreparedStatement ps = con.prepareStatement(sql);
			ps.setString(1,s);
			ResultSet rs =ps.executeQuery();
			String uname = null;
			if(rs.next()) uname = rs.getString("Username");
			
			if(user.equals(uname))
			{
				out.write("<br/><br/>You have already issued the book with Id ("+s+")");
			}
			else
			{
String sql1 = "INSERT INTO TranBook VALUES(?,?,?)" ;
			PreparedStatement ps1 = con.prepareStatement(sql1);
			ps1.setString(1,user);
			ps1.setString(2,s);
			ps1.setDate(3,new Date(session.getLastAccessedTime()));
			ps1.executeUpdate();
			
			String sql2 = "SELECT TotalBooks FROM Books WHERE Id = ?";
			PreparedStatement ps2 = con.prepareStatement(sql2);
			ps2.setString(1,s);
			ResultSet rs2 =ps2.executeQuery();
			rs2.next();
			String btotal = rs2.getString("TotalBooks");
			int bt = Integer.parseInt(btotal);
			bt = bt-1;
			
			String sql3 = "UPDATE Books SET TotalBooks = ? WHERE Id = ?" ;
			PreparedStatement ps3 = con.prepareStatement(sql3);
			ps3.setInt(1,bt);
			ps3.setString(2,s);
			ps3.executeUpdate();
			
			out.write("<br/><br/>The book with Id ("+s+") is issued !...");	
			}
			}
		
					
	}
	else
	{
		out.write("<br/><br/>Please select book to issue ....... ");			
	}		
	
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
